spring:
  datasource:
    url: jdbc:postgresql://ddpg-cmilnd6n7f5s73a4uaqg-a.frankfurt-postgres.render.com:5432/postgresql_database_5wo2?user=postgresql_database_5wo2_user&password=ons7nbaZVnwaKD4SzA5Vk4fgZqeYT1nM