spring:
  datasource:
    url: jdbc:postgresql://dpg-ckmk798710pc73d2mb60-a.frankfurt-postgres.render.com:5432/postgresql_database_dxq8?user=postgresql_database_dxq8_user&password=mjs2SLg9wqKE5r5jXI8yiYHmwl9UPYvt